The `npm install` command failed in my project. Analyze the following error output and fix it, potentially involving changes to `package.json`.
NPM Error Output:
```
prisma:warn Prisma failed to detect the libssl/openssl version to use, and may not work as expected. Defaulting to "openssl-1.1.x".
Please manually install OpenSSL and try installing Prisma again.
prisma:warn Prisma failed to detect the libssl/openssl version to use, and may not work as expected. Defaulting to "openssl-1.1.x".
Please manually install OpenSSL and try installing Prisma again.
Error: Prisma schema validation - (get-dmmf wasm)
Error code: P1012
[1;91merror[0m: [1mError parsing attribute "@relation": The relation fields `patientProfile` on Model `User` and `user` on Model `Patient` both provide the `references` argument in the @relation attribute. You have to provide it only on one of the two fields.[0m
  [1;94m-->[0m  [4mprisma/schema.prisma:23[0m
[1;94m   | [0m
[1;94m22 | [0m  patientProfileId    String?       @unique
[1;94m23 | [0m  [1;91mpatientProfile      Patient?      @relation(fields: [patientProfileId], references: [id])[0m
[1;94m24 | [0m
[1;94m   | [0m
[1;91merror[0m: [1mError parsing attribute "@relation": The relation fields `patientProfile` on Model `User` and `user` on Model `Patient` both provide the `references` argument in the @relation attribute. You have to provide it only on one of the two fields.[0m
  [1;94m-->[0m  [4mprisma/schema.prisma:43[0m
[1;94m   | [0m
[1;94m42 | [0m  userId             String?   @unique
[1;94m43 | [0m  [1;91muser               User?     @relation(fields: [userId], references: [id])[0m
[1;94m44 | [0m
[1;94m   | [0m
[1;91merror[0m: [1mError parsing attribute "@relation": The relation fields `patientProfile` on Model `User` and `user` on Model `Patient` both provide the `fields` argument in the @relation attribute. You have to provide it only on one of the two fields.[0m
  [1;94m-->[0m  [4mprisma/schema.prisma:23[0m
[1;94m   | [0m
[1;94m22 | [0m  patientProfileId    String?       @unique
[1;94m23 | [0m  [1;91mpatientProfile      Patient?      @relation(fields: [patientProfileId], references: [id])[0m
[1;94m24 | [0m
[1;94m   | [0m
[1;91merror[0m: [1mError parsing attribute "@relation": The relation fields `patientProfile` on Model `User` and `user` on Model `Patient` both provide the `fields` argument in the @relation attribute. You have to provide it only on one of the two fields.[0m
  [1;94m-->[0m  [4mprisma/schema.prisma:43[0m
[1;94m   | [0m
[1;94m42 | [0m  userId             String?   @unique
[1;94m43 | [0m  [1;91muser               User?     @relation(fields: [userId], references: [id])[0m
[1;94m44 | [0m
[1;94m   | [0m
[1;91merror[0m: [1mError parsing attribute "@relation": The relation fields `user` on Model `Patient` and `patientProfile` on Model `User` both provide the `references` argument in the @relation attribute. You have to provide it only on one of the two fields.[0m
  [1;94m-->[0m  [4mprisma/schema.prisma:43[0m
[1;94m   | [0m
[1;94m42 | [0m  userId             String?   @unique
[1;94m43 | [0m  [1;91muser               User?     @relation(fields: [userId], references: [id])[0m
[1;94m44 | [0m
[1;94m   | [0m
[1;91merror[0m: [1mError parsing attribute "@relation": The relation fields `user` on Model `Patient` and `patientProfile` on Model `User` both provide the `references` argument in the @relation attribute. You have to provide it only on one of the two fields.[0m
  [1;94m-->[0m  [4mprisma/schema.prisma:23[0m
[1;94m   | [0m
[1;94m22 | [0m  patientProfileId    String?       @unique
[1;94m23 | [0m  [1;91mpatientProfile      Patient?      @relation(fields: [patientProfileId], references: [id])[0m
[1;94m24 | [0m
[1;94m   | [0m
[1;91merror[0m: [1mError parsing attribute "@relation": The relation fields `user` on Model `Patient` and `patientProfile` on Model `User` both provide the `fields` argument in the @relation attribute. You have to provide it only on one of the two fields.[0m
  [1;94m-->[0m  [4mprisma/schema.prisma:43[0m
[1;94m   | [0m
[1;94m42 | [0m  userId             String?   @unique
[1;94m43 | [0m  [1;91muser               User?     @relation(fields: [userId], references: [id])[0m
[1;94m44 | [0m
[1;94m   | [0m
[1;91merror[0m: [1mError parsing attribute "@relation": The relation fields `user` on Model `Patient` and `patientProfile` on Model `User` both provide the `fields` argument in the @relation attribute. You have to provide it only on one of the two fields.[0m
  [1;94m-->[0m  [4mprisma/schema.prisma:23[0m
[1;94m   | [0m
[1;94m22 | [0m  patientProfileId    String?       @unique
[1;94m23 | [0m  [1;91mpatientProfile      Patient?      @relation(fields: [patientProfileId], references: [id])[0m
[1;94m24 | [0m
[1;94m   | [0m
[1;91merror[0m: [1mError validating field `medicalRecordEntry` in model `LabResult`: The relation field `medicalRecordEntry` on model `LabResult` is missing an opposite relation field on the model `MedicalRecordEntry`. Either run `prisma format` or add it manually.[0m
  [1;94m-->[0m  [4mprisma/schema.prisma:129[0m
[1;94m   | [0m
[1;94m128 | [0m  medicalRecordEntryId  String?
[1;94m129 | [0m  [1;91mmedicalRecordEntry    MedicalRecordEntry? @relation(fields: [medicalRecordEntryId], references: [id])[0m
[1;94m130 | [0m
[1;94m   | [0m
[1;91merror[0m: [1mError validating field `medicalRecordEntry` in model `DicomStudy`: The relation field `medicalRecordEntry` on model `DicomStudy` is missing an opposite relation field on the model `MedicalRecordEntry`. Either run `prisma format` or add it manually.[0m
  [1;94m-->[0m  [4mprisma/schema.prisma:154[0m
[1;94m   | [0m
[1;94m153 | [0m  medicalRecordEntryId String?
[1;94m154 | [0m  [1;91mmedicalRecordEntry   MedicalRecordEntry? @relation(fields: [medicalRecordEntryId], references: [id])[0m
[1;94m155 | [0m
[1;94m   | [0m

Validation Error Count: 10
[Context: getDmmf]

Prisma CLI Version : 5.22.0
npm error code 1
npm error path /home/user/studio
npm error command failed
npm error command sh -c prisma generate
npm error A complete log of this run can be found in: /home/.npm/_logs/2025-05-29T23_18_48_590Z-debug-0.log

```